language: node_js
node_js:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
branches:
  except:
    - image
sudo: required
before_install:
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:chris-lea/redis-server
  - sudo apt-get update
  - sudo apt-get install -y redis-server
